/**
 * Smart Zone System — catalogue local (fallback + seed)
 * Coordonnées indicatives autour du campus Manouba (à affiner en prod).
 */
const ZONES_CATALOG = {
  zones: [
    {
      id: 'zone_engineering_manouba',
      name: 'École supérieure des ingénieurs de Manouba',
      latitude: 36.8142,
      longitude: 10.0642,
      radius: 140,
      type: 'engineering',
      enterMessage: 'Entrée dans la zone Ingénierie ⚙️🌱',
    },
    {
      id: 'zone_informatics_ensi',
      name: 'École nationale des sciences informatiques',
      latitude: 36.8129,
      longitude: 10.0624,
      radius: 120,
      type: 'informatics',
      enterMessage: 'Entrée dans la zone Informatique 💻🌿',
    },
    {
      id: 'zone_business_isg',
      name: 'Zone Commerce & Finance (ISG / gestion)',
      latitude: 36.8124,
      longitude: 10.0648,
      radius: 125,
      type: 'business_finance',
      enterMessage: 'Entrée dans la zone Finance durable 📊🌱',
    },
  ],
  contents: [
    {
      id: 'eng_mission_canopee',
      zone_id: 'zone_engineering_manouba',
      content_type: 'mission',
      title: 'Canopée campus',
      description: 'Cartographiez mentalement trois zones ombragées du campus pour la biodiversité.',
      reward_xp: 40,
      reward_coins: 12,
      badge_id: 'badge_eco_engineer',
      play_payload: { kind: 'mission_ack' },
    },
    {
      id: 'eng_quiz_geomatics',
      zone_id: 'zone_engineering_manouba',
      content_type: 'quiz',
      title: 'Géomatique & végétation',
      description: 'Une image satellite sert souvent à estimer…',
      reward_xp: 35,
      reward_coins: 10,
      play_payload: {
        kind: 'quiz',
        question: 'Quel indice est le plus utilisé pour estimer la biomasse végétale à grande échelle ?',
        choices: ['NDVI', 'Humidité relative seule', 'Pression barométrique'],
        answerIndex: 0,
      },
    },
    {
      id: 'eng_game_sequence',
      zone_id: 'zone_engineering_manouba',
      content_type: 'game',
      title: 'Mémoire terrain',
      description: 'Reproduisez la séquence des échantillons.',
      reward_xp: 30,
      reward_coins: 15,
      play_payload: { kind: 'sequence', labels: ['🌿', '📍', '🧪'], sequence: [0, 2, 1] },
    },
    {
      id: 'info_quiz_green_it',
      zone_id: 'zone_informatics_ensi',
      content_type: 'quiz',
      title: 'Green IT',
      description: 'Réduire l’empreinte du numérique sur le campus.',
      reward_xp: 40,
      reward_coins: 14,
      play_payload: {
        kind: 'quiz',
        question: 'Quelle pratique réduit le plus la consommation énergétique des serveurs ?',
        choices: ['Virtualisation & mutualisation', 'Écrans plus lumineux', 'Wi-Fi désactivé sur téléphones'],
        answerIndex: 0,
      },
    },
    {
      id: 'info_game_logic',
      zone_id: 'zone_informatics_ensi',
      content_type: 'game',
      title: 'Suite logique',
      description: 'Trouvez la valeur manquante.',
      reward_xp: 25,
      reward_coins: 10,
      play_payload: { kind: 'logic_series', series: [2, 4, 6, 8], missingIndex: 2, options: [5, 6, 7] },
    },
    {
      id: 'info_mission_sustainable_code',
      zone_id: 'zone_informatics_ensi',
      content_type: 'mission',
      title: 'Code durable',
      description: 'Identifiez une fonctionnalité à optimiser (moins d’appels réseau) dans une appli campus fictive.',
      reward_xp: 45,
      reward_coins: 18,
      play_payload: { kind: 'mission_ack' },
    },
    {
      id: 'biz_mission_invest',
      zone_id: 'zone_business_isg',
      content_type: 'mission',
      title: 'Investissement éco-responsable',
      description: 'Choisissez un portefeuille théorique orienté transition bas-carbone.',
      reward_xp: 40,
      reward_coins: 20,
      play_payload: { kind: 'mission_ack' },
    },
    {
      id: 'biz_game_decision',
      zone_id: 'zone_business_isg',
      content_type: 'game',
      title: 'Scénario finance verte',
      description: 'Privilégier court terme ou transition long terme ?',
      reward_xp: 35,
      reward_coins: 16,
      play_payload: {
        kind: 'decision',
        prompt: 'Un fonds campus doit allouer 100k : quelle option maximise impact CO₂ évité sur 10 ans (scénario simplifié) ?',
        choices: ['Photovoltaïque sur toits', 'Marketing événementiel'],
        correctIndex: 0,
      },
    },
    {
      id: 'biz_quiz_esg',
      zone_id: 'zone_business_isg',
      content_type: 'quiz',
      title: 'ESG sur le campus',
      description: 'Finance durable & reporting.',
      reward_xp: 30,
      reward_coins: 12,
      play_payload: {
        kind: 'quiz',
        question: 'Que signifie la lettre « E » dans ESG ?',
        choices: ['Environmental (Environnemental)', 'Equity (Équité)', 'Efficiency (Efficacité)'],
        answerIndex: 0,
      },
    },
  ],
};

Object.freeze(ZONES_CATALOG);
