# Generated by Django 5.2.13 on 2026-04-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health_score', models.FloatField(default=100.0)),
                ('coordinates', models.TextField(help_text='JSON list of [lat, lng] point bounds max length 50')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(choices=[('DAILY', 'Daily'), ('EVENT', 'Event'), ('QR', 'QR Checkpoint')], max_length=50)),
                ('target_score', models.IntegerField()),
                ('reward_xp', models.IntegerField()),
                ('reward_coins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealWorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('club_name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('qr_code_secret', models.CharField(max_length=32, unique=True)),
                ('reward_xp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mission')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_new_discovery', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.player')),
            ],
        ),
    ]
